export const RESERVE_SERVICE = "RESERVE_SERVICE";
export const UPDATE_CALENDAR = "UPDATE_CALENDAR";
export const CANCEL_SERVICE = "CANCEL_SERVICE";

export const SERVICES_DATA_LOADED = "SERVICES_DATA_LOADED";
export const CALENDAR_DATA_LOADED = "CALENDAR_DATA_LOADED";

export const FILTER_SERVICE_LIST = "FILTER_SERVICE_LIST";

export const TOGGLE_APP_FORM = "TOGGLE_APP_FORM";

export const SEND_SELECTED_DATE_TIME = "SEND_SELECTED_DATE_TIME";