export const RESERVE_SERVICE = "RESERVE_SERVICE";
export const SERVICES_DATA_LOADED = "SERVICES_DATA_LOADED";
export const CALENDAR_DATA_LOADED = "CALENDAR_DATA_LOADED";
export const CANCEL_SERVICE = "CANCEL_SERVICE";